### ISSUE TITLE
Creating <Testcase Name>_Failure_Log.txt file ONLY incase of any Testcase Failure

### ISSUE THREAD

**Issue by Parumugam** [lgirdk/boardfarm#107]
Hello All,

We see that, in the results folder, there is a single file named "Console.log" getting created which dumps all the console output of all executions. This will make the debugging job difficult to see which section is for our particular execution.

Can we think of a way to create a individual log file per testcase, BUT only incase of Failure with name <Testcase Name>)_Failure_log.txt?

Also, I would like the Automation script to collect as much relative log information as possible incase of Failure so that, we shall avoid Re-run or Manual execution of the scenario. Please let me know your thoughts.

**Comment by mattsm** [comment]
I'm not sure there isn't a reason to always log all devices. I start this effort here:

https://github.com/lgirdk/boardfarm/pull/110

Let me know what you think.

**Comment by Parumugam** [comment]
Agree @mattsm . As the logging is happening by mentioning the start & stop of the testcases, its easy to find the logs of respective testcase, so there is no need to have a logic which logs the messages only during failure. As #110 is validated and merged, I am closing this issue.
