### ISSUE TITLE
Creating Docker Containers with all Required services installed by default

### ISSUE THREAD

**Issue by Parumugam** [lgirdk/boardfarm#108]
Hello All,

During Automation, as we dont have dedicated Boardfarms allocated for engieers, they will be using a BF which is free. But the Containers associate to that BF might not have all required services (Example: SNMP) and hence the script fails.

Can we please ensure all the Docker containers have basic services (we can come up with the list of Basic services) during the creation of containers itself?

Thanks,
Pranesh

**Comment by mattsm** [comment]
I think the best bet is to take the bft-node/Dockerfile and create your own versions in your own overlay.

Also, you can create a script which source deploy-boardfarm-nodes.sh in this repo and creates the containers in the desired configuration as well as building the nodes.

The one thing I will do here in this repo is make the Docker container image configurable from the deploy scripts:

https://github.com/lgirdk/boardfarm/pull/111

-M

-M

**Comment by mattsm** [comment]
I will add, we can add a few basic things to the containers in this repo- but "the requirements" are different for everyone so if they are getting exotic we should add our own in our own overlay.

**Comment by Parumugam** [comment]
I agree @mattsm , this list can grow. So the agreement is, the respective Automation Engineer needs to prepare their environment to execute their test. Also, Matthew & Michele are working on the namespace thing to ensure the LAN Containers have internet access to download the required package.

With this agreement, I am closing this issue.
