### ISSUE TITLE
Multiple Lan Containers with same VLAN (To Simulate Multiple LAN Clients)

### ISSUE THREAD

**Issue by Parumugam** [lgirdk/boardfarm#109]
Hello All,

We have scenarios which needs multiple LAN Clients, so if we need to automate them, we need more than 1 Docker LAN Containers with same VLAN.

I understand, we are working on this but having some hiccups. Just wanted to document the ask so we can keep work on it and get a solution.

**Comment by mattsm** [comment]
This is the in-progress work:

https://github.com/lgirdk/boardfarm/pull/100

Not working just yet though

**Comment by mattsm** [comment]
Tested working, please review and test pull request

**Comment by mattsm** [comment]
If this is working, can you please update here and close this issue?

**Comment by ketantewari** [comment]
Multiple LAN container implementation is verified on AMS BF1. We identified following issues which were resolved after verification:
- iptables rule conflict between containers.
- inconsistency in DHCP IP assignment between containers.

Also need to ensure that VLANs are allowed on the trunk connected to Boardfarm
