### ISSUE TITLE
Not able to view the GUI of Cable Modems

### ISSUE THREAD

**Issue by Parumugam** [lgirdk/boardfarm#133]
From Netherlands, When we try to access the GUI of Cable Modem, we are not able to access them.

is there any network restrcitions blocking this?

@mgualco-contractor @preddy-contractor , Can you please add more details about the configurations we have did?

**Comment by preddy-contractor** [comment]
Gualco, Michele: comments:-
==================
Hi all,
What I did is: 
1.	VPN to CBN
2.	locally (on my laptop) open a sock5 tunnel to a lan container at the CBN lab: ssh -D <port> root@<lan IP> -p <lanPort> -vv
3.	make sure the lan container can access 192.168.0.1 (CPE must have an ip 192.168.0.x)
4.	locally (on my laptop) open FFox, and set the proxy to localhost 9999 socks5
5.	in the FFox address bar: 192.168.0.1
6.	on the lan prompt I can see the that the comms channels are being closed
the webpage cannot be accessed.

The same test to the LGI lab in Amsterdam works, and the page renders on  FFox
Ketan suspects the CBN firewall is closing the sock5 connections
