### ISSUE TITLE
Add support for exporting data to MongoDB

### ISSUE THREAD

**Issue by mattsm** [lgirdk/boardfarm#245]

**Comment by mbanders** [comment]
Do you simply want `test_results.json` posted into a collecting in a MongoDB? If so this should be pretty easy.

I would just add an option like `mongodb_server` in `config.py` and if that is set, connect and push the results.

**Comment by mattsm** [comment]
I think we want to store something more along the line of what we post to ELK.

**Comment by mbanders** [comment]
Done with commit https://github.com/lgirdk/boardfarm/commit/4558a71339d4cf897aee61b1ab62c6decae0d1af
