### ISSUE TITLE
Better approach on Connection closed by foreign host issue

### ISSUE THREAD

**Issue by Parumugam** [lgirdk/boardfarm#316]
Hi Matt,

Can we make a better approach on killing the session when there are no RX/TX on ARM/ATOM Console for 5 mins?

Can we increase this time to 15 mins given that, this is double the time for any provisioning? 

Also, is it possible to read whether the board is locked by Jenkins User or any other user and then decide to kill it or not?

**Comment by Parumugam** [comment]
Understood from Matthew that, this 5 Min Restriction is relaxed in SVL Now. Is it temporary? or can we close this ticket?

**Comment by mattsm** [comment]
Yea, let's close this.. we can revisit if needed
