### ISSUE TITLE
SnmpHelper.py throws an exception - maybe if BFT_OVERLAY isn't set correctly?

### ISSUE THREAD

**Issue by mbanders** [lgirdk/boardfarm#347]
Test cases:

```
# Set directories to whatever you have
export BFT_OVERLAY="/home/whatever/ /home/whatever2/ ..."
# Go to some other directory
cd /tmp/
# Run this command
python -c 'from boardfarm import devices'
```

We see a lot of errors when doing the above. It might have something to do with the mibs files are found here: https://github.com/lgirdk/boardfarm/blob/master/boardfarm/lib/SnmpHelper.py#L105

**Comment by mattsm** [comment]
I think this might be fixed... it was an issue with ```pip install -e .```  not being run in some places. The above change might fix it.

**Comment by mbanders** [comment]
The issue was when you try to run `bft` from a directory somewhere else - not near a `boardfarm` directory. Fixed with https://github.com/lgirdk/boardfarm/commit/0f72af4d7e488f874ab94b81118b1f10ce2124c9
