### ISSUE TITLE
Allow bft to be run from any directory

### ISSUE THREAD

**Issue by mattsm** [lgirdk/boardfarm#67]
There are current a few issues when running boardfarm (bft) command from a different directory than it resides it. This issue is to track that problem and hopefully fix it.

**Comment by mattsm** [comment]
This leads to bft being installed somewhere, and further a step toward making bft importable as a module.

**Comment by mbanders** [comment]
I have this working on my machine. I can run bft from anywhere, but there's one tiny catch: we need to move almost all files to a new subdirectory and call it "boardfarm". So it would basically look like this:

```
# Main directory
README.md
LICENSE
setup.py
# Almost everything else moved to a boardfarm subdirectory
boardfarm/
boardfarm/bft
boardfarm/devices/
boardfarm/tests/
...etc
```

Then boardfarm becomes something we can install and import from anywhere, and we can run "bft" command line. It's great.

But adding a directory and moving files there is probably difficult because there's a lot of dependencies on the layout of this project.

**Comment by mattsm** [comment]
Can we add symlinks to keep most work flows going?

bft -> boardfarm/bft ?

-M

**Comment by mbanders** [comment]
A working example of boardfarm as a module, and running bft from anywhere is here in the demo branch: https://github.com/lgirdk/boardfarm/tree/demo

The most important files are [setup.py](https://github.com/lgirdk/boardfarm/blob/demo/setup.py) and [Boardfarm.py](https://github.com/lgirdk/boardfarm/blob/demo/boardfarm/Boardfarm.py)

Other things I had to do:

```sh
# Move lib directory out of tests (we don't want to import tests to get simple functions)
mv boardfarm/tests/lib boardfarm/lib
# Change imports in all python files, including overlays
sed -i 's/from devices import/from boardfarm.devices import/' *.py
sed -i 's/import lib/from boardfarm import lib/' *.py
sed -i 's/from lib import/from boardfarm.lib import/' *.py
sed -i 's/from library import/from boardfarm.library import/' *.py
sed -i 's/import config/from boardfarm import config/' *.py
sed -i 's/from lib./from boardfarm.lib./' *.py
```

You get the idea.

**Comment by mattsm** [comment]
This will probably be one of the more painful activities, can you work on a script with the right mv and sed commands for this repo, boardfarm-docsis, and some of our other private repos?

**Comment by mbanders** [comment]
Thanks to: https://github.com/lgirdk/boardfarm/commit/d1edde8bd8ed082625effb60da31de3d4159b28f and https://github.com/lgirdk/boardfarm/commit/fc372522bec7a4e370d07330260a73fd6665a015 and https://github.com/lgirdk/boardfarm/commit/aff2e7fa0f01ffb6ce3ce575c95d857a6a4cf56d#diff-2eeaed663bd0d25b7e608891384b7298

We are at the point where after the user does `pip install -e .` to install boardfarm, we do this from anywhere:

```sh
$ bft --version
bft 1.1.0

$ bft -l
       BitTorrentB2B - Single UDP/Bittorrent flow back-to-back
     BitTorrentBasic - Super simple simulation of BitTorrent traffic
    ...

$ bft -i
       Name            Model   Auto                        LAN                        WAN  Notes
 new_device          Unknown   True                                                        Unknown device with docker containers attached to WAN/LAN
  qemux86-1          qemux86   True                                                        QEMU emulated devices
    ...
```

I doubt running the tests works yet. That will take more work.

**Comment by mbanders** [comment]
Looks like I finally succeeded now that boardfarm and overlays are pip installed and many imports fixed. Most recent code change that made this possible: https://github.com/lgirdk/boardfarm/commit/65d4f1d63b6bc3e9c6ea679028d172e6b155caa7

Now w can do this:

```sh
export BFT_OVERLAY='my overlay directories'
export BFT_CONFIG='http://whatever/bf_config'
bft -b myboard -x flash
```
