### ISSUE TITLE
Test log and result.html should be put into folder with DUT name.

### ISSUE THREAD

**Issue by lynnlincbn** [lgirdk/boardfarm#69]
Our test team using SSH to trigger boardfarm to test not using Jenkisn.

If mv1-1-1 and mv1-1-2 are test on same time, it's too hard to search test log which is mv1-1-1 or mv1-1-2
The result.html will be covered by last test case.
Can you help to add new request for test log and result?
ex:
The log and result of mv1-1-1 shoud be put into /results/mv1-1-1/
The log and result of mv1-1-2 shoud be put into /results/mv1-1-2/
Thanks.

**Comment by NeroChenCBN** [comment]
Dear Matthew
  When more test was trigger on same user , the last result will cover the first.
  And we start teach NTL how to use it . the people of use boardfarm will more and more.
  So we need different result log every trigger.
  We hope log path can follow CM\Date\Date-Time.html , and same date test case log put there too.
  EX. 
         boardfarm\result\MV1-1-1\20180815\20180815_170503_result.html
         boardfarm\result\MV1-1-1\20180815\NTL7465LG_2180-20180815-170031.txt
         ...

**Comment by mattsm** [comment]
I understand the issue, but for now why don't you checkout a new boardfarm and boardfarm-cbn repo and run from there?

**Comment by NeroChenCBN** [comment]
Which file we should modify it?

**Comment by mattsm** [comment]
Two things... the message above is a suggestion to run each invocation of boardfarm from a new clean dir. You can do a fresh git clone or do a git clean or something to clear the old results files. If you are running two tests at once they should be in different directories so you would have two copies of the boardfarm repo and any other overlays you are using.

Second, we can add support for this feature... but it needs to be allocated time and someone to do the work. Also, we need to make sure that it does not break anyone else that already assumes that the results dir has the latest results regardless of which station you are running from.

**Comment by Parumugam** [comment]
Hello All, I see this request is an interesting one. Can someone work on this please? As we are expecting more testcases to be automated and executed, seperating the results folder by Date make sense.

**Comment by mattsm** [comment]
You can already set the output dir manually with the -o or --output dir option.

-M

**Comment by mbanders** [comment]
Closing since you can already do this with the `-o` option. If you had a script to trigger jobs you could do this for example:

```sh
outdir="example_`date +%Y_%m_%d`"
bft -b myboard -t travisci -o $outdir
# and results will be stored in "example_2019_09_06"
```
