### ISSUE TITLE
Add function to decide DUT test scope

### ISSUE THREAD

**Issue by SyHuangCBN** [lgirdk/boardfarm#82]
Due to we have several Boardfarm stations and different function test.

We need to add filter function to parser which DUT runs specific environment.

**Comment by mattsm** [comment]
This is not exactly what is requested but you can filter of the config by doing the following:

./bft -b board_type -f feature.*wifi

And if it matches a feature.*wifi regex it will select from those boards. This is just sharing that info for now.

**Comment by mattsm** [comment]
Ok, see https://github.com/lgirdk/boardfarm/pull/83 for the implementation of this
