### ISSUE TITLE
Fix html email to show proper ip addr of wan/lan and http proxy

### ISSUE THREAD

**Issue by mattsm** [lgirdk/boardfarm#93]

**Comment by mbanders** [comment]
The results html currenly only shows:

* wan debian
* lan debian

You just want their IP address listed right after that?

**Comment by mattsm** [comment]
It would be nice if we can iterate through all the devices and show their proper connection command if possible, or maybe just ip and port.

For some devices, we don't talk over ssh at all, so a server url for those might be better? E.g. acs server.

**Comment by mbanders** [comment]
Showing ip address of devices: https://github.com/lgirdk/boardfarm/commit/d3217871e45eee6253919f8e977f5beb9990491d

**Comment by mbanders** [comment]
Created separate issue for just the HTTP proxy: https://github.com/lgirdk/boardfarm/issues/332
